default:
	cp ../squeak.js .
	cp ../globals.js .
	cp ../vm.*.js .
	cp ../jit.js .
	cp ../run/squeakjs.css .
	mkdir lib/
	cp ../lib/*.js lib/
	mkdir plugins/
	cp ../plugins/*.js plugins/

clean:
	rm *.css
	rm -rf lib/
	rm -rf plugins/
	rm squeak.js
	rm globals.js
	rm vm.*.js
	rm jit.js
