default:
	cp ../squeak.js .
	cp ../vm.js .
	cp ../jit.js .
	cp ../run/squeakjs.css .
	mkdir plugins/
	cp ../plugins/*.js plugins/

clean:
	rm *.css
	rm -rf plugins/
	rm squeak.js
	rm vm.js
	rm jit.js
